"""add tables table to new column

Revision ID: 41d63870a9c8
Revises: e435648903d3
Create Date: 2026-01-04 16:44:51.388514

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41d63870a9c8"
down_revision = "e435648903d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_updated", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.drop_column("last_updated")

    # ### end Alembic commands ###
