"""added category model

Revision ID: 63bed5f022af
Revises: 8b6a9367fc90
Create Date: 2026-01-01 02:14:54.451097

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63bed5f022af"
down_revision = "8b6a9367fc90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category")
    # ### end Alembic commands ###
