"""nullable statemant add to tables table

Revision ID: 6a49d4927c22
Revises: 41d63870a9c8
Create Date: 2026-01-04 16:51:52.402704

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6a49d4927c22"
down_revision = "41d63870a9c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.alter_column(
            "last_updated", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tables", schema=None) as batch_op:
        batch_op.alter_column(
            "last_updated", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    # ### end Alembic commands ###
