"""empty message

Revision ID: 8b6a9367fc90
Revises: 48f3e7a275a3
Create Date: 2025-12-23 21:48:08.240800

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b6a9367fc90"
down_revision = "48f3e7a275a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
