"""add to tables domains

Revision ID: e435648903d3
Revises: a0fcdad12a9f
Create Date: 2026-01-04 02:39:39.354837

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e435648903d3"
down_revision = "a0fcdad12a9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "RESERVED", "OCCUPIED", name="tablestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tables")
    # ### end Alembic commands ###
